import { describe, expect, it } from "vitest";

import {
  hashBlock,
  hashDocument,
  normalizeInstructionMarkdown,
  sha256Hex,
} from "./normalize.js";

/** Shorthand: normalized document hash of a markdown string. */
const docHash = (content: string) => normalizeInstructionMarkdown(content).hash;

describe("normalizeInstructionMarkdown - whitespace", () => {
  it("hashes CRLF and LF documents identically", () => {
    const lf = "# Title\n\nUse pnpm.\n";
    const crlf = "# Title\r\n\r\nUse pnpm.\r\n";
    expect(docHash(crlf)).toBe(docHash(lf));
  });

  it("ignores trailing spaces, tab runs and extra blank lines", () => {
    const clean = "# Title\n\nUse pnpm always.\n";
    const messy = "#  Title  \n\n\n\nUse \t pnpm   always.   \n\n";
    expect(docHash(messy)).toBe(docHash(clean));
  });

  it("treats paragraph hard-wrapping as formatting, not drift", () => {
    const wrapped = "Run the linter\nbefore every commit\nwithout exception.\n";
    const single = "Run the linter before every commit without exception.\n";
    expect(docHash(wrapped)).toBe(docHash(single));
    expect(normalizeInstructionMarkdown(wrapped).blocks).toHaveLength(1);
  });

  it("returns zero blocks and a stable hash for empty and blank documents", () => {
    for (const content of ["", "\n", "   \n\n\t\n"]) {
      const doc = normalizeInstructionMarkdown(content);
      expect(doc.blocks).toEqual([]);
      expect(doc.hash).toBe(sha256Hex(""));
    }
  });
});

describe("normalizeInstructionMarkdown - headings", () => {
  it("canonicalizes ATX headings, dropping closing hashes", () => {
    expect(docHash("##  Setup  ##\n")).toBe(docHash("## Setup\n"));
    const [block] = normalizeInstructionMarkdown("## Setup\n").blocks;
    expect(block).toMatchObject({ kind: "heading", text: "## Setup", managed: false });
  });

  it("keeps heading level significant", () => {
    expect(docHash("# Setup\n")).not.toBe(docHash("## Setup\n"));
  });
});

describe("normalizeInstructionMarkdown - fences", () => {
  it("preserves fence content verbatim, whitespace included", () => {
    const a = "```sh\n  echo one\n\n  echo two\n```\n";
    const b = "```sh\necho one\n\necho two\n```\n";
    const [block] = normalizeInstructionMarkdown(a).blocks;
    expect(block).toMatchObject({ kind: "fence", text: "```sh\n  echo one\n\n  echo two\n```" });
    expect(docHash(a)).not.toBe(docHash(b));
  });

  it("canonicalizes tilde fences and info-string spacing to backticks", () => {
    expect(docHash("~~~~  sh\nls\n~~~~\n")).toBe(docHash("```sh\nls\n```\n"));
  });

  it("never parses markers or markdown inside a fence", () => {
    const doc = normalizeInstructionMarkdown(
      "```md\n# not a heading\n<!-- gitmesh:managed -->\n- not a list\n```\n",
    );
    expect(doc.blocks).toHaveLength(1);
    expect(doc.blocks[0]!.kind).toBe("fence");
    expect(doc.blocks[0]!.text).toContain("<!-- gitmesh:managed -->");
    expect(doc.blocks[0]!.managed).toBe(false);
  });

  it("closes an unterminated fence at end of document", () => {
    const doc = normalizeInstructionMarkdown("```sh\nls\n");
    expect(doc.blocks).toEqual([
      expect.objectContaining({ kind: "fence", text: "```sh\nls\n```" }),
    ]);
  });
});

describe("normalizeInstructionMarkdown - lists", () => {
  it("canonicalizes unordered markers to '-'", () => {
    expect(docHash("* one\n* two\n")).toBe(docHash("- one\n- two\n"));
    expect(docHash("+ one\n+ two\n")).toBe(docHash("- one\n- two\n"));
  });

  it("canonicalizes ordered punctuation and joins continuation lines", () => {
    const a = "1) first rule\n   spanning two lines\n2) second\n";
    const b = "1. first rule spanning two lines\n2. second\n";
    expect(docHash(a)).toBe(docHash(b));
  });

  it("keeps nesting indentation significant and separates runs on blank lines", () => {
    expect(docHash("- a\n  - b\n")).not.toBe(docHash("- a\n- b\n"));
    const doc = normalizeInstructionMarkdown("- a\n\n- b\n");
    expect(doc.blocks.map((block) => block.kind)).toEqual(["list", "list"]);
  });

  it("distinguishes a list from a paragraph with the same text", () => {
    expect(hashBlock("list", "- x")).not.toBe(hashBlock("paragraph", "- x"));
    expect(docHash("- item\n")).not.toBe(docHash("item\n"));
  });
});

describe("normalizeInstructionMarkdown - markers", () => {
  it("strips third-party wrapper comments so wrapped content is zero drift", () => {
    const wrapped =
      "<!-- Generated by Ruler -->\n\n<!-- Source: .ruler/style.md -->\nUse tabs.\n";
    expect(docHash(wrapped)).toBe(docHash("Use tabs.\n"));
  });

  it("strips multi-line wrapper comments", () => {
    const wrapped = "<!--\n  managed by rulesync\n  do not edit\n-->\nUse tabs.\n";
    expect(docHash(wrapped)).toBe(docHash("Use tabs.\n"));
  });

  it("keeps an inline comment inside a text line as content", () => {
    const inline = "Use tabs. <!-- always -->\n";
    expect(docHash(inline)).not.toBe(docHash("Use tabs.\n"));
  });

  it("flags blocks inside gitmesh managed markers, without affecting hashes", () => {
    const doc = normalizeInstructionMarkdown(
      "Intro.\n\n<!-- gitmesh:managed adapter=claude-code -->\n# Managed\n\n- rule one\n<!-- /gitmesh:managed -->\n\nOutro.\n",
    );
    expect(doc.blocks.map((block) => [block.kind, block.managed])).toEqual([
      ["paragraph", false],
      ["heading", true],
      ["list", true],
      ["paragraph", false],
    ]);
    expect(docHash("# Managed\n")).toBe(
      normalizeInstructionMarkdown("<!-- gitmesh:managed -->\n# Managed\n<!-- /gitmesh:managed -->\n").hash,
    );
  });
});

describe("hashing", () => {
  it("is order-sensitive at the document level", () => {
    expect(docHash("# A\n\n# B\n")).not.toBe(docHash("# B\n\n# A\n"));
  });

  it("derives the document hash from the ordered block hashes", () => {
    const doc = normalizeInstructionMarkdown("# A\n\ntext\n");
    expect(doc.hash).toBe(hashDocument(doc.blocks));
    expect(doc.blocks[0]!.hash).toBe(hashBlock("heading", "# A"));
  });

  it("produces stable, deterministic hex digests", () => {
    expect(sha256Hex("")).toBe(
      "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    );
    expect(docHash("# A\n")).toBe(docHash("# A\n"));
  });
});
